#
# GMP MPN sources
#

set(MPN_GENERIC_SOURCES)
macro(add_generic_source name obj)
    set(filename ${CMAKE_CURRENT_BINARY_DIR}/mpn/${name}.c)
    #set(MPN_GENERIC_SOURCES ${MPN_GENERIC_SOURCES} ${filename})
	#set_source_files_properties(${filename} PROPERTIES OPERATION_${name} 1)	
	file(WRITE ${filename} "#define OPERATION_${name} 1\n#include <mpn/generic/${obj}.c>")
	#add_custom_command(OUTPUT ${filename}	    
	#    COMMAND echo "#define OPERATION_${name} 1//">${filename}
	#	COMMAND echo "#include \"generic/${obj}.c\"">>${filename})
		
	set(MPN_GENERIC_SOURCES ${MPN_GENERIC_SOURCES} ${filename})

endmacro()

file(COPY ${CMAKE_HOME_DIRECTORY}/cmake/msvc/${__arch__}/perfsqr.h DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/mpn)
##################################################################
#
# below code gerate from Linux x86_64(NO_ASM) build with scripte
#
# #! /bin/sh
# items=$(ls mpn/*.c -l | awk '{ if($11) print " " $9 "@" $11}')
# for item in ${items}
# do
#   name=$(echo $item | awk -F @ '{print $1}')
#   obj=$(echo $item | awk -F @ '{print $2}')
#   name=$(basename $name)
#   obj=$(basename $obj)
#   name=${name%.*}
#   obj=${obj%.*}
# 
#   comments='# diff'
#   [ $name == $obj ] && comments=
# 
#   echo  "add_generic_source(${name} ${obj}) $comments"
# done
#
###################################################################

add_generic_source(add_1 add_1) 
add_generic_source(add add) 
add_generic_source(add_err1_n add_err1_n) 
add_generic_source(add_err2_n add_err2_n) 
add_generic_source(add_err3_n add_err3_n) 
add_generic_source(addmul_1 addmul_1) 
add_generic_source(add_n add_n) 
add_generic_source(add_n_sub_n add_n_sub_n) 
add_generic_source(and_n logops_n) # diff
add_generic_source(andn_n logops_n) # diff
add_generic_source(bdiv_dbm1c bdiv_dbm1c) 
add_generic_source(bdiv_q_1 bdiv_q_1) 
add_generic_source(bdiv_q bdiv_q) 
add_generic_source(bdiv_qr bdiv_qr) 
add_generic_source(binvert binvert) 
add_generic_source(broot broot) 
add_generic_source(brootinv brootinv) 
add_generic_source(bsqrt bsqrt) 
add_generic_source(bsqrtinv bsqrtinv) 
add_generic_source(cmp cmp) 
add_generic_source(cnd_add_n cnd_add_n) 
add_generic_source(cnd_sub_n cnd_sub_n) 
add_generic_source(cnd_swap cnd_swap) 
add_generic_source(comb_tables comb_tables) 
add_generic_source(com com) 
add_generic_source(copyd copyd) 
add_generic_source(copyi copyi) 
add_generic_source(dcpi1_bdiv_q dcpi1_bdiv_q) 
add_generic_source(dcpi1_bdiv_qr dcpi1_bdiv_qr) 
add_generic_source(dcpi1_divappr_q dcpi1_divappr_q) 
add_generic_source(dcpi1_div_q dcpi1_div_q) 
add_generic_source(dcpi1_div_qr dcpi1_div_qr) 
add_generic_source(dive_1 dive_1) 
add_generic_source(diveby3 diveby3) 
add_generic_source(divexact divexact) 
add_generic_source(divis divis) 
add_generic_source(div_q div_q) 
add_generic_source(div_qr_1 div_qr_1) 
add_generic_source(div_qr_1n_pi1 div_qr_1n_pi1) 
add_generic_source(div_qr_2 div_qr_2) 
add_generic_source(div_qr_2n_pi1 div_qr_2n_pi1) 
add_generic_source(div_qr_2u_pi1 div_qr_2u_pi1) 
add_generic_source(divrem_1 divrem_1) 
add_generic_source(divrem_2 divrem_2) 
add_generic_source(divrem divrem) 
add_generic_source(dump dump) 
add_generic_source(fib2_ui fib2_ui) 
add_generic_source(gcd_1 gcd_1) 
add_generic_source(gcd gcd) 
add_generic_source(gcdext_1 gcdext_1) 
add_generic_source(gcdext gcdext) 
add_generic_source(gcdext_lehmer gcdext_lehmer) 
add_generic_source(gcd_subdiv_step gcd_subdiv_step) 
add_generic_source(get_d get_d) 
add_generic_source(get_str get_str) 
add_generic_source(hamdist popham) # diff
add_generic_source(hgcd2 hgcd2) 
add_generic_source(hgcd2_jacobi hgcd2_jacobi) 
add_generic_source(hgcd_appr hgcd_appr) 
add_generic_source(hgcd hgcd) 
add_generic_source(hgcd_jacobi hgcd_jacobi) 
add_generic_source(hgcd_matrix hgcd_matrix) 
add_generic_source(hgcd_reduce hgcd_reduce) 
add_generic_source(hgcd_step hgcd_step) 
add_generic_source(invertappr invertappr) 
add_generic_source(invert invert) 
add_generic_source(ior_n logops_n) # diff
add_generic_source(iorn_n logops_n) # diff
add_generic_source(jacbase jacbase) 
add_generic_source(jacobi_2 jacobi_2) 
add_generic_source(jacobi jacobi) 
add_generic_source(lshift lshift) 
add_generic_source(lshiftc lshiftc) 
add_generic_source(matrix22_mul1_inverse_vector matrix22_mul1_inverse_vector) 
add_generic_source(matrix22_mul matrix22_mul) 
add_generic_source(mod_1_1 mod_1_1) 
add_generic_source(mod_1_2 mod_1_2) 
add_generic_source(mod_1_3 mod_1_3) 
add_generic_source(mod_1_4 mod_1_4) 
add_generic_source(mod_1 mod_1) 
add_generic_source(mod_34lsub1 mod_34lsub1) 
add_generic_source(mode1o mode1o) 
add_generic_source(mu_bdiv_q mu_bdiv_q) 
add_generic_source(mu_bdiv_qr mu_bdiv_qr) 
add_generic_source(mu_divappr_q mu_divappr_q) 
add_generic_source(mu_div_q mu_div_q) 
add_generic_source(mu_div_qr mu_div_qr) 
add_generic_source(mul_1 mul_1) 
add_generic_source(mul_basecase mul_basecase) 
add_generic_source(mul mul) 
add_generic_source(mul_fft mul_fft) 
add_generic_source(mullo_basecase mullo_basecase) 
add_generic_source(mullo_n mullo_n) 
add_generic_source(mulmid_basecase mulmid_basecase) 
add_generic_source(mulmid mulmid) 
add_generic_source(mulmid_n mulmid_n) 
add_generic_source(mulmod_bnm1 mulmod_bnm1) 
add_generic_source(mul_n mul_n) 
add_generic_source(nand_n logops_n) # diff
add_generic_source(neg neg) 
add_generic_source(nior_n logops_n) # diff
add_generic_source(nussbaumer_mul nussbaumer_mul) 
add_generic_source(perfpow perfpow) 
add_generic_source(perfsqr perfsqr) 
add_generic_source(popcount popham) # diff
add_generic_source(pow_1 pow_1) 
add_generic_source(powlo powlo) 
add_generic_source(powm powm) 
add_generic_source(pre_divrem_1 pre_divrem_1) 
add_generic_source(pre_mod_1 pre_mod_1) 
add_generic_source(random2 random2) 
add_generic_source(random random) 
add_generic_source(redc_1 redc_1) 
add_generic_source(redc_2 redc_2) 
add_generic_source(redc_n redc_n) 
add_generic_source(remove remove) 
add_generic_source(rootrem rootrem) 
add_generic_source(rshift rshift) 
add_generic_source(sbpi1_bdiv_q sbpi1_bdiv_q) 
add_generic_source(sbpi1_bdiv_qr sbpi1_bdiv_qr) 
add_generic_source(sbpi1_divappr_q sbpi1_divappr_q) 
add_generic_source(sbpi1_div_q sbpi1_div_q) 
add_generic_source(sbpi1_div_qr sbpi1_div_qr) 
add_generic_source(scan0 scan0) 
add_generic_source(scan1 scan1) 
add_generic_source(sec_add_1 sec_aors_1) # diff
add_generic_source(sec_div_qr sec_div) # diff
add_generic_source(sec_div_r sec_div) # diff
add_generic_source(sec_invert sec_invert) 
add_generic_source(sec_mul sec_mul) 
add_generic_source(sec_pi1_div_qr sec_pi1_div) # diff
add_generic_source(sec_pi1_div_r sec_pi1_div) # diff
add_generic_source(sec_powm sec_powm) 
add_generic_source(sec_sqr sec_sqr) 
add_generic_source(sec_sub_1 sec_aors_1) # diff
add_generic_source(sec_tabselect sec_tabselect) 
add_generic_source(set_str set_str) 
add_generic_source(sizeinbase sizeinbase) 
add_generic_source(sqr_basecase sqr_basecase) 
add_generic_source(sqr sqr) 
add_generic_source(sqrlo_basecase sqrlo_basecase) 
add_generic_source(sqrlo sqrlo) 
add_generic_source(sqrmod_bnm1 sqrmod_bnm1) 
add_generic_source(sqrtrem sqrtrem) 
add_generic_source(sub_1 sub_1) 
add_generic_source(sub sub) 
add_generic_source(sub_err1_n sub_err1_n) 
add_generic_source(sub_err2_n sub_err2_n) 
add_generic_source(sub_err3_n sub_err3_n) 
add_generic_source(submul_1 submul_1) 
add_generic_source(sub_n sub_n) 
add_generic_source(tdiv_qr tdiv_qr) 
add_generic_source(toom22_mul toom22_mul) 
add_generic_source(toom2_sqr toom2_sqr) 
add_generic_source(toom32_mul toom32_mul) 
add_generic_source(toom33_mul toom33_mul) 
add_generic_source(toom3_sqr toom3_sqr) 
add_generic_source(toom42_mul toom42_mul) 
add_generic_source(toom42_mulmid toom42_mulmid) 
add_generic_source(toom43_mul toom43_mul) 
add_generic_source(toom44_mul toom44_mul) 
add_generic_source(toom4_sqr toom4_sqr) 
add_generic_source(toom52_mul toom52_mul) 
add_generic_source(toom53_mul toom53_mul) 
add_generic_source(toom54_mul toom54_mul) 
add_generic_source(toom62_mul toom62_mul) 
add_generic_source(toom63_mul toom63_mul) 
add_generic_source(toom6h_mul toom6h_mul) 
add_generic_source(toom6_sqr toom6_sqr) 
add_generic_source(toom8h_mul toom8h_mul) 
add_generic_source(toom8_sqr toom8_sqr) 
add_generic_source(toom_couple_handling toom_couple_handling) 
add_generic_source(toom_eval_dgr3_pm1 toom_eval_dgr3_pm1) 
add_generic_source(toom_eval_dgr3_pm2 toom_eval_dgr3_pm2) 
add_generic_source(toom_eval_pm1 toom_eval_pm1) 
add_generic_source(toom_eval_pm2 toom_eval_pm2) 
add_generic_source(toom_eval_pm2exp toom_eval_pm2exp) 
add_generic_source(toom_eval_pm2rexp toom_eval_pm2rexp) 
add_generic_source(toom_interpolate_12pts toom_interpolate_12pts) 
add_generic_source(toom_interpolate_16pts toom_interpolate_16pts) 
add_generic_source(toom_interpolate_5pts toom_interpolate_5pts) 
add_generic_source(toom_interpolate_6pts toom_interpolate_6pts) 
add_generic_source(toom_interpolate_7pts toom_interpolate_7pts) 
add_generic_source(toom_interpolate_8pts toom_interpolate_8pts) 
add_generic_source(trialdiv trialdiv) 
add_generic_source(xnor_n logops_n) # diff
add_generic_source(xor_n logops_n) # diff
add_generic_source(zero zero) 
add_generic_source(zero_p zero_p)